#%RAML 0.8
title: Booking
baseUri: http://dddsample.marcusoncode.se/booking/{version}
version: v1

/cargos:
  get:
    description: All booked cargos
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "cargos": [
                      {
                          "arrival_deadline": "0001-01-01T00:00:00Z",
                          "destination": "CNHKG",
                          "misrouted": false,
                          "origin": "SESTO",
                          "routed": false,
                          "tracking_id": "ABC123"
                      },
                      {
                          "arrival_deadline": "0001-01-01T00:00:00Z",
                          "destination": "SESTO",
                          "misrouted": false,
                          "origin": "AUMEL",
                          "routed": false,
                          "tracking_id": "FTL456"
                      }
                  ]
              }
  post:
    description: Book a new cargo.
    body:
      application/json:
        example: |
          {
              "origin": "SESTO",
              "destination": "DEHAM",
              "arrival_deadline": "2016-03-24T23:00:00Z"
          }
      
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "tracking_id": "ABC123"
              }
